V1.0.0
eastgenomics/TSO500Reporter pull request #4
Opened 2021-11-12 14:56 UTC by spaul91

Completed development of V1.0.0 of TSO500Parser. Intended to be used in the helios pipeline to generate TMB/MSI reports in the final step.

Components:

- __main__.py: executable to point to input files and generate TMB/MSI reports
- parser.py: classes for manipulating input files
- plotter: function for plotting TMB/MSI
- reporter: functions for writing the report
- templates: HTML/CSS templates

2021-11-12 14:56 UTC, pep8speaks commented
Hello @spaul91! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`setup.py`](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/setup.py):

> [Line 3:1](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/setup.py#L3): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 7:1](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/setup.py#L7): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 9:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/setup.py#L9): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (165 > 79 characters)

* In the file [`tso500reporter/__main__.py`](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/__main__.py):

> [Line 16:1](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/__main__.py#L16): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 20:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/__main__.py#L20): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (136 > 79 characters)
> [Line 21:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/__main__.py#L21): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 22:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/__main__.py#L22): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (93 > 79 characters)
> [Line 23:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/__main__.py#L23): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)
> [Line 29:1](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/__main__.py#L29): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 38:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/__main__.py#L38): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 79 characters)
> [Line 45:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/__main__.py#L45): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (119 > 79 characters)
> [Line 49:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/__main__.py#L49): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (119 > 79 characters)
> [Line 53:5](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/__main__.py#L53): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 56:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/__main__.py#L56): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 79 characters)
> [Line 60:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/__main__.py#L60): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)

* In the file [`tso500reporter/constants.py`](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/constants.py):

> [Line 1:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/constants.py#L1): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 2:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/constants.py#L2): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)

* In the file [`tso500reporter/parser.py`](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py):

> [Line 14:1](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py#L14): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 19:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py#L19): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 28:37](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py#L28): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 28:38](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py#L28): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 28:54](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py#L28): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 28:55](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py#L28): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 28:70](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py#L28): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 28:71](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py#L28): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 28:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py#L28): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (143 > 79 characters)
> [Line 28:101](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py#L28): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 28:102](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py#L28): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 28:131](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py#L28): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 28:132](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py#L28): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 30:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py#L30): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 31:80](https://github.com/eastgenomics/TSO500Reporter/blob/326da517d0b755f5c272c6896e6f804c0e141e2f/tso500reporter/parser.py#L31): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 31:88](https://github.com/eastgenomics/TSO5 [...]

2021-11-18 14:41 UTC, mattgarner requested changes
> Reviewed 10 of 16 files at r1, 3 of 6 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: all files reviewed, 5 unresolved discussions (waiting on @spaul91)

*[a discussion](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MonMCozCNgrk3QVz-zO:-MonMCozCNgrk3QVz-zP:b-6og4md) (no related file):*
Great readme!

---
___
*[setup.py, line 10 at r3](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MonMY791dxVneZ8WWy-:-MonMY791dxVneZ8WWy0:bqdg9f1) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/18463ef05d15eefa077f1ce99813e66a0b48c6ac/setup.py#L10)):*
> ```
> 0.1
> ```
Semver please!
https://semver.org/
___
*[setup.py, line 15 at r3](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MonMxU6-BSZONF_A3Bq:-MonMxU6-BSZONF_A3Br:by18qim) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/18463ef05d15eefa077f1ce99813e66a0b48c6ac/setup.py#L15)):*
> ```
> http://github.com/spaul91/TSO500Reporter
> ```
Could we refer to the GLH org repo instead here? 
`https://github.com/eastgenomics/TSO500Reporter`
___
*[tso500reporter/constants.py, line 4 at r3](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MonP_Hr1FygKpyFeVay:-MonP_HsATmBCGHg9Gj-:b-1timqv) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/18463ef05d15eefa077f1ce99813e66a0b48c6ac/tso500reporter/constants.py#L4)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 
>         "Total MSI Sites Unstable",
>         "Percent Unstable MSI Sites"]
> TMB_FIELDS = ["Total TMB",
>         "Coding Region Size in Megabases",
>         "Number of Passing Eligible Variants"]
> ```
</details>

Trailing whitespace
___
*[tso500reporter/parser.py, line 377 at r3](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MonTpYk7iBB6OEc6hyO:-MonTpYk7iBB6OEc6hyP:b-plvszh) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/18463ef05d15eefa077f1ce99813e66a0b48c6ac/tso500reporter/parser.py#L377)):*
> ```
> ChainMap(*record)
> ```
Neat, not seen this before. 
Is there any possibility that the resulting object has duplicate keys in our scenario?


<!-- Sent from Reviewable.io -->

2021-11-19 11:28 UTC, spaul91 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: 14 of 16 files reviewed, 5 unresolved discussions (waiting on @mattgarner)

*[a discussion](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MonMCozCNgrk3QVz-zO:-MorwtAj-DfqFRJ21lAN:b-ucfknh) (no related file):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Great readme!
</blockquote></details>

Thanks!

---
___
*[setup.py, line 10 at r3](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MonMY791dxVneZ8WWy-:-MorwI0E6GTLaS0a1tS4:bqztwf6) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/18463ef05d15eefa077f1ce99813e66a0b48c6ac/setup.py#L10)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> 0.1
> ```
Semver please!
https://semver.org/
</blockquote></details>

I've changed this to V1.0.0, since the public API (?) is stable (i.e. I don't think I'll change the way you interact with the module for the forseeable future)
___
*[setup.py, line 15 at r3](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MonMxU6-BSZONF_A3Bq:-MorwHPv8BliGDo2E_ui:b-896fix) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/18463ef05d15eefa077f1ce99813e66a0b48c6ac/setup.py#L15)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> http://github.com/spaul91/TSO500Reporter
> ```
Could we refer to the GLH org repo instead here? 
`https://github.com/eastgenomics/TSO500Reporter`
</blockquote></details>

Done.
___
*[tso500reporter/constants.py, line 4 at r3](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MonP_Hr1FygKpyFeVay:-MorwG2lE23KIWsyalfy:b-mtlwbi) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/18463ef05d15eefa077f1ce99813e66a0b48c6ac/tso500reporter/constants.py#L4)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> 
>         "Total MSI Sites Unstable",
>         "Percent Unstable MSI Sites"]
> TMB_FIELDS = ["Total TMB",
>         "Coding Region Size in Megabases",
>         "Number of Passing Eligible Variants"]
> ```
Trailing whitespace
</blockquote></details>

Removed whitespace
___
*[tso500reporter/parser.py, line 377 at r3](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MonTpYk7iBB6OEc6hyO:-Morukbb4FU0s1JAOfUI:b-lz8xih) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/18463ef05d15eefa077f1ce99813e66a0b48c6ac/tso500reporter/parser.py#L377)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ChainMap(*record)
> ```
Neat, not seen this before. 
Is there any possibility that the resulting object has duplicate keys in our scenario?
</blockquote></details>

Currently no, but that's only because of the layout of CombinedVariantOutput.tsv. If the files change in any way after an updated (e.g. adding a field that's duplicated across [Analysis Details] and [Sequencing Run Details]), then one of them will be overwritten. ChainMap does this silently unfortunately... I think I should try to handle this a little better, but I'm neutral on that.


<!-- Sent from Reviewable.io -->

2021-11-23 09:23 UTC, mattgarner requested changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: all files reviewed, 2 unresolved discussions (waiting on @mattgarner and @spaul91)

___
*[tso500reporter/exceptions.py, line 13 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpB5PoRE0O3NvEUI3_Y:-MpB5PoRE0O3NvEUI3_Z:ba99asc) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/exceptions.py#L13)):*
> ```
> salary
> ```
salary?


<!-- Sent from Reviewable.io -->

2021-11-23 16:59 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: all files reviewed, 3 unresolved discussions (waiting on @mattgarner and @spaul91)

___
*[tso500reporter/templates/template.html, line 5 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCil3J7TlRPbdztuD_:-MpCil3K2uYlY_3Z29BS:b-9iahgn) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/templates/template.html#L5)):*
> ```HTML
>     <div class="divHeader">{{run_name}}</div>
>     <head>
>         <link rel="stylesheet" href="{{template_dir}}/styles.css">
> ```

this stylesheet won't be included as its a hardcoded path, if you generate the html and send it to someone else this path won't exist and it won't open with the styling.

Since it's a small amount of css I'd just include them in `<style></style>` tags in the head


<!-- Sent from Reviewable.io -->

2021-11-23 17:07 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: all files reviewed, 8 unresolved discussions (waiting on @mattgarner and @spaul91)

___
*[examples/report.html, line 5 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCkjR_-SlzHZMnDxRe:-MpCkjR_-SlzHZMnDxRf:b8rwj8y) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/examples/report.html#L5)):*
> ```HTML
>     <div class="divHeader">211015_A01303_0033_AHLGJVDRXY</div>
>     <head>
>         <link rel="stylesheet" href="/home/pauls4/workspace/development/TSO500Reporter/tso500reporter/templates/styles.css">
> ```

needs to either be from a cdn or written in to the file
___
*[examples/report.html, line 12 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCkfh0BMiU1vdRVQ8l:-MpCkfh0BMiU1vdRVQ8m:bax4726) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/examples/report.html#L12)):*
> ```HTML
>         <div>
>             <h1>Tumour Mutational Burden</h1>
>             <img src=img/tmb.png id="tmb">
> ```

this wants to be the image string written to the file
___
*[examples/report.html, line 128 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCkqBCEhGVj0Z8lLAe:-MpCkqBCEhGVj0Z8lLAf:bnj7hl0) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/examples/report.html#L128)):*
> ```HTML
>         <div>
>             <h1>Microsatellite Instability</h1>
>             <img src=img/msi.png id="msi">
> ```

same as above
___
*[tso500reporter/__main__.py, line 10 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCkSqo-kguLtUeCoS8:-MpCkSqo-kguLtUeCoS9:b8hylwn) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/__main__.py#L10)):*
> ```
> from . import parser
> from . import plotter
> from . import reporter
> ```
this could just be one line as `from . import parser, plotter, reporter`
___
*[tso500reporter/reporter.py, line 56 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCjdhfCDnhmfJrHBIn:-MpCjdhfCDnhmfJrHBIo:bgbpih2) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/reporter.py#L56)):*
> ```Python
> 
>     # handle PNG embedding
>     if embed:
> ```

any reason you wouldn't want to just write the png into the report? These aren't being hosted from a server as a page and are just a flat file, so they need all the content writing


<!-- Sent from Reviewable.io -->

2021-11-23 17:14 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: all files reviewed, 10 unresolved discussions (waiting on @mattgarner and @spaul91)

___
*[tso500reporter/__main__.py, line 21 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpClHUT9E7DfMIe901w:-MpClHUT9E7DfMIe901x:byrh1xg) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/__main__.py#L21)):*
> ```Python
>     parser = argparse.ArgumentParser()
> 
>     parser.add_argument("-d", "--variant-data", 
> ```

there's a few pep8 issues on under indentation, I think it is better to format these like this to keep the pep8 bot happy:
```
parser.add_argument(
    "-d", "--variant-data", nargs="+", required=True,
    help="filepaths to <SAMPLE>_*CombinedVariantOutput.tsv files",
)

```
___
*[tso500reporter/__main__.py, line 24 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpClxOKAeRZwJ7-kS0l:-MpClxOKAeRZwJ7-kS0m:bwvm9af) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/__main__.py#L24)):*
> ```Python
>             help="filepaths to <SAMPLE>_*CombinedVariantOutput.tsv files", 
>             nargs="+", required=True)
>     parser.add_argument("-s", "--samplesheet", 
> ```

there's a few trailing whitespaces, do you have linting turned on to make these visible? in reviewable they show up as red dots


<!-- Sent from Reviewable.io -->

2021-11-23 19:29 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: all files reviewed, 11 unresolved discussions (waiting on @mattgarner and @spaul91)

___
*[tso500reporter/templates/template.html, line 5 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpDGK872UVvUhTpRBCu:-MpDGK872UVvUhTpRBCv:b72lb7x) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/templates/template.html#L5)):*
> ```HTML
>     <div class="divHeader">{{run_name}}</div>
>     <head>
>         <link rel="stylesheet" href="{{template_dir}}/styles.css">
> ```

I'd also consider adding bootstrap CDN as a stylesheet for nicer styling:
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">`


<!-- Sent from Reviewable.io -->

2021-11-26 10:49 UTC, spaul91 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: 7 of 17 files reviewed, 11 unresolved discussions (waiting on @jethror1, @mattgarner, and @spaul91)

___
*[examples/report.html, line 5 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCkjR_-SlzHZMnDxRe:-MpGn9VwDI8hJo1ScJjW:bt9ogsk) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/examples/report.html#L5)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

needs to either be from a cdn or written in to the file
</blockquote></details>

CSS is now inline (see below)
___
*[examples/report.html, line 12 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCkfh0BMiU1vdRVQ8l:-MpQr9pY9hnViC_ltwV5:b-ujzlh1) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/examples/report.html#L12)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this wants to be the image string written to the file
</blockquote></details>

I don't understand, sorry. This is the image data as a base-64 string, not a reference to the PNG file
___
*[tso500reporter/__main__.py, line 10 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCkSqo-kguLtUeCoS8:-MpGlHCABInQkFhWkN8Y:bb6un1j) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/__main__.py#L10)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

> ```
> from . import parser
> from . import plotter
> from . import reporter
> ```
this could just be one line as `from . import parser, plotter, reporter`
</blockquote></details>

Done
___
*[tso500reporter/__main__.py, line 21 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpClHUT9E7DfMIe901w:-MpGlIrzBAj0eRD9yOO0:bb6un1j) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/__main__.py#L21)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

there's a few pep8 issues on under indentation, I think it is better to format these like this to keep the pep8 bot happy:
```
parser.add_argument(
    "-d", "--variant-data", nargs="+", required=True,
    help="filepaths to <SAMPLE>_*CombinedVariantOutput.tsv files",
)

```
</blockquote></details>

Done
___
*[tso500reporter/__main__.py, line 24 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpClxOKAeRZwJ7-kS0l:-MpGlJra2pHwAVIcUTA4:bb6un1j) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/__main__.py#L24)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

there's a few trailing whitespaces, do you have linting turned on to make these visible? in reviewable they show up as red dots
</blockquote></details>

Done
___
*[tso500reporter/exceptions.py, line 13 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpB5PoRE0O3NvEUI3_Y:-MpGk28G38VPHUPVoi6u:b-dljx09) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/exceptions.py#L13)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> salary
> ```
salary?
</blockquote></details>

🤦‍♀️

Sorry. I google'd an example to structure the exception because I couldn't quite remember how to do it. Fixed
___
*[tso500reporter/reporter.py, line 56 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCjdhfCDnhmfJrHBIn:-MpGiqHcB4S0vJhArDKG:byljzn8) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/reporter.py#L56)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

any reason you wouldn't want to just write the png into the report? These aren't being hosted from a server as a page and are just a flat file, so they need all the content writing
</blockquote></details>

This is what `to_base64()` is doing; it reads in PNGs saved to disk in the previous step, and converts them to base64 encoding. The base64 string ends up being written to the report directly. If your question was more along the lines of why write the plots to disk at all in the intermediate step, then it's because that was the simplest approach I could think of. Also, it gives you flexibility if you ever want to share the plots without the report for any reason (powerpoint presentations etc.)
___
*[tso500reporter/templates/template.html, line 5 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCil3J7TlRPbdztuD_:-MpGmUEY4eDnxGEDyQby:b-diibhf) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/templates/template.html#L5)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this stylesheet won't be included as its a hardcoded path, if you generate the html and send it to someone else this path won't exist and it won't open with the styling.

Since it's a small amount of css I'd just include them in `<style></style>` tags in the head
</blockquote></details>

Fair point, I've changed this behaviour to import the CSS from a template and write it as inline CSS directly.
___
*[tso500reporter/templates/template.html, line 5 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpDGK872UVvUhTpRBCu:-MpGmLyA2p9SkdJqmgLC:br07jag) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/templates/template.html#L5)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I'd also consider adding bootstrap CDN as a stylesheet for nicer styling:
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">`
</blockquote></details>

I tried it and it removes the row/column dividers :(


<!-- Sent from Reviewable.io -->

2021-11-26 10:51 UTC, spaul91 commented
___
*[tso500reporter/__main__.py, line 21 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpClHUT9E7DfMIe901w:-MpQrUe7DBx2M6Z3_CV5:b-nzfyys) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/__main__.py#L21)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Not done! I removed the whitespace, forgot about PEP8 issue


<!-- Sent from Reviewable.io -->

2021-11-26 11:56 UTC, jethror1 requested changes
> Reviewed 4 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: 11 of 17 files reviewed, 7 unresolved discussions (waiting on @mattgarner and @spaul91)

___
*[examples/report.html, line 12 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCkfh0BMiU1vdRVQ8l:-MpR0ahc-iRuApF7WRe5:bkci8e3) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/examples/report.html#L12)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I don't understand, sorry. This is the image data as a base-64 string, not a reference to the PNG file
</blockquote></details>

when I was doing the PR it was written as a path like this:
```
 <h1>Tumour Mutational Burden</h1>
            <img src=img/tmb.png id="tmb">
            <h2>data</h2>
            <table border="1" class="dataframe">
```

^ that would not load the image when sent to others, your image string you have now is fine
___
*[tso500reporter/reporter.py, line 56 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCjdhfCDnhmfJrHBIn:-MpR1Am60P8fBstm50F9:bckw69v) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/reporter.py#L56)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

This is what `to_base64()` is doing; it reads in PNGs saved to disk in the previous step, and converts them to base64 encoding. The base64 string ends up being written to the report directly. If your question was more along the lines of why write the plots to disk at all in the intermediate step, then it's because that was the simplest approach I could think of. Also, it gives you flexibility if you ever want to share the plots without the report for any reason (powerpoint presentations etc.)
</blockquote></details>

My original question was why would you not be writing the image string into the report? if `embed` is not set then it just adds a path into the html, which would not load anything as a standalone html file that is given to the scientists.

re writing plots to you can use `BytesIO` for this which saves the plot as a file object in memory and can be treat as a normal file, example here: https://github.com/eastgenomics/athena/blob/a6122eea8adaa4358f31953ea2034f86796948f0/bin/coverage_report_single.py#L52

In terms of having this as an app in a workflow, would you then have an app that outputs the .html report and separate plots? If the png is embded in the html at the same quality as what is being written to .png files they can just copy paste them out of the reports if they wanted them. I'd try and avoid outputting more files than necessary from apps
___
*[tso500reporter/templates/template.html, line 5 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpDGK872UVvUhTpRBCu:-MpR4cLT4hQOmG0p8yDO:b8mzkms) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/templates/template.html#L5)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I tried it and it removes the row/column dividers :(
</blockquote></details>

`pd.to_html()` supports standard CSS table classes for styling:

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_html.html
https://getbootstrap.com/docs/4.0/content/tables/

something like `to_html(classes=['table-striped', 'table-hover', 'table-bordered'])` might be nice.

You can also add padding to the whole content either by adding to the top css or inline in the body tag with something like `style=padding:5%`


<!-- Sent from Reviewable.io -->

2021-11-26 13:20 UTC, spaul91 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: 11 of 17 files reviewed, 7 unresolved discussions (waiting on @jethror1, @mattgarner, and @spaul91)

___
*[examples/report.html, line 12 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCkfh0BMiU1vdRVQ8l:-MpROljyCYaCXkopUWRm:b6f4f4p) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/examples/report.html#L12)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

when I was doing the PR it was written as a path like this:
```
 <h1>Tumour Mutational Burden</h1>
            <img src=img/tmb.png id="tmb">
            <h2>data</h2>
            <table border="1" class="dataframe">
```

^ that would not load the image when sent to others, your image string you have now is fine
</blockquote></details>

Ah ok, sorry for the confusion
___
*[tso500reporter/reporter.py, line 56 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCjdhfCDnhmfJrHBIn:-MpRMv6R1KOSJpdm73Ic:b25duvm) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/reporter.py#L56)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

My original question was why would you not be writing the image string into the report? if `embed` is not set then it just adds a path into the html, which would not load anything as a standalone html file that is given to the scientists.

re writing plots to you can use `BytesIO` for this which saves the plot as a file object in memory and can be treat as a normal file, example here: https://github.com/eastgenomics/athena/blob/a6122eea8adaa4358f31953ea2034f86796948f0/bin/coverage_report_single.py#L52

In terms of having this as an app in a workflow, would you then have an app that outputs the .html report and separate plots? If the png is embded in the html at the same quality as what is being written to .png files they can just copy paste them out of the reports if they wanted them. I'd try and avoid outputting more files than necessary from apps
</blockquote></details>

Understood, apologies for the confusion. `embed` would always be set in the app, so the end result in DNANexus would only be reports with embedded plots. The intermediate PNG files would be destroyed when the compute session ends, since they aren't uploaded back. It's this way because I assumed it wouldn't make much difference, and storing the object in memory would require me to write an additional function. Happy to discuss further if there are issues with the way it is currently
___
*[tso500reporter/templates/template.html, line 5 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpDGK872UVvUhTpRBCu:-MpRO_gD0PtQt6QOOTX8:bg21e9n) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/templates/template.html#L5)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

`pd.to_html()` supports standard CSS table classes for styling:

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_html.html
https://getbootstrap.com/docs/4.0/content/tables/

something like `to_html(classes=['table-striped', 'table-hover', 'table-bordered'])` might be nice.

You can also add padding to the whole content either by adding to the top css or inline in the body tag with something like `style=padding:5%`

</blockquote></details>

`table-striped` is really pretty! I'll do that thank you :)


<!-- Sent from Reviewable.io -->

2021-11-29 14:45 UTC, spaul91 commented
___
*[tso500reporter/templates/template.html, line 5 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpDGK872UVvUhTpRBCu:-Mpg8ze0COwlkwUAwW9Y:b-brn2sd) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/templates/template.html#L5)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

`table-striped` is really pretty! I'll do that thank you :)
</blockquote></details>

Now includes bootstrap v3.3.7


<!-- Sent from Reviewable.io -->

2021-11-29 14:47 UTC, spaul91 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: 10 of 17 files reviewed, 7 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[examples/report.html, line 128 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCkqBCEhGVj0Z8lLAe:-Mpg9LEC7uSg7rEF6G51:bb6un1j) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/examples/report.html#L128)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done
___
*[tso500reporter/__main__.py, line 21 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpClHUT9E7DfMIe901w:-Mpg9OtW-fm2OAdTAhqW:bb6un1j) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/__main__.py#L21)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Not done! I removed the whitespace, forgot about PEP8 issue
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-11-29 16:06 UTC, jethror1 requested changes
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: 11 of 17 files reviewed, 4 unresolved discussions (waiting on @jethror1, @mattgarner, and @spaul91)

___
*[tso500reporter/reporter.py, line 56 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCjdhfCDnhmfJrHBIn:-MpgRN-C5gD3k5RSM-Ks:b3ier6m) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/reporter.py#L56)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Understood, apologies for the confusion. `embed` would always be set in the app, so the end result in DNANexus would only be reports with embedded plots. The intermediate PNG files would be destroyed when the compute session ends, since they aren't uploaded back. It's this way because I assumed it wouldn't make much difference, and storing the object in memory would require me to write an additional function. Happy to discuss further if there are issues with the way it is currently
</blockquote></details>

it's not a massive thing, was just wondering about the choice / utility of _not_ embedding the plots, but nothing to worry about :) 
___
*[tso500reporter/templates/template.html, line 5 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpDGK872UVvUhTpRBCu:-MpgR19XAkpDY2OMWkk5:b-hkj9wd) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/templates/template.html#L5)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Now includes bootstrap v3.3.7
</blockquote></details>

sorry forgot to add `table` to the list of css classes to give it the standard nice table formatting, could you add it too please?  


<!-- Sent from Reviewable.io -->

2021-11-29 17:32 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: 11 of 17 files reviewed, 4 unresolved discussions (waiting on @jethror1, @mattgarner, and @spaul91)

___
*[tso500reporter/templates/template.html, line 5 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpDGK872UVvUhTpRBCu:-MpgkB-_CkIzka_AHIp-:b-yu20ml) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/templates/template.html#L5)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

sorry forgot to add `table` to the list of css classes to give it the standard nice table formatting, could you add it too please?  
</blockquote></details>

^ would also consider some amount padding to the sides


<!-- Sent from Reviewable.io -->

2021-11-30 11:32 UTC, spaul91 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: 10 of 17 files reviewed, 4 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[tso500reporter/reporter.py, line 56 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpCjdhfCDnhmfJrHBIn:-MpkbBPcE-U6vk6GQW7_:b-jty3tg) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/reporter.py#L56)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

it's not a massive thing, was just wondering about the choice / utility of _not_ embedding the plots, but nothing to worry about :) 
</blockquote></details>

Sure :) marking this discussion as resolved if that's ok
___
*[tso500reporter/templates/template.html, line 5 at r4](https://reviewable.io/reviews/eastgenomics/tso500reporter/4#-MpDGK872UVvUhTpRBCu:-MpkbOQ1CkGUMOcmGZc8:b-bu91xm) ([raw file](https://github.com/eastgenomics/tso500reporter/blob/f2d45396f8b5557a103e750c3811c9532f0d7f61/tso500reporter/templates/template.html#L5)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

^ would also consider some amount padding to the sides
</blockquote></details>

Updated


<!-- Sent from Reviewable.io -->

2021-11-30 12:17 UTC, jethror1 approved these changes
> Reviewed 2 of 9 files at r5, 1 of 1 files at r6, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: all files reviewed, 2 unresolved discussions (waiting on @mattgarner)



<!-- Sent from Reviewable.io -->

2021-11-30 12:18 UTC, jethror1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: all files reviewed, 2 unresolved discussions (waiting on @mattgarner)



<!-- Sent from Reviewable.io -->

2021-12-01 12:42 UTC, mattgarner approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/tso500reporter/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spaul91)



<!-- Sent from Reviewable.io -->

2021-12-01 12:42 UTC, merged